apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-deployment
        image: 987242725346.dkr.ecr.us-east-1.amazonaws.com/database_ecr_repo:v0.1
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "passwors"
        ports:
        - containerPort: 3306
