apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:latest
    env:
    - name: DB_PASSWORD
      value: "passwors"
    - name: DATABASE
      value: "employees"
    ports:
    - containerPort: 3306

  
