apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-db-rs
  labels:
    app: mysql-db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql
        image: 987242725346.dkr.ecr.us-east-1.amazonaws.com/database_ecr_repo:v0.1
        env:
    - name: DBPWD
      value:  "passwors"
    - name: DATABASE
      value: "employees"
        ports:
        - containerPort: 3306
      
