apiVersion: v1
kind: Service
metadata:
  name: mysql-db-svc
  labels:
    app: mysql-db
spec:
  selector:
    app: mysql-db
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  type: NodePort
