apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-deployment
  labels:
    app: employees
spec:
  replicas: 3 # number of replicas to create
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: employees-deployment
        image: 987242725346.dkr.ecr.us-east-1.amazonaws.com/application_ecr_repo:v0.1
        ports:
        - containerPort: 8080 # the port Python app is listening on
        env:
        - name: DBHOST
          value: "mysql-svc.mysql-namespace.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DB_PASSWORD
          value: "passwors"
