apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 3 # number of replicas to create
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: 987242725346.dkr.ecr.us-east-1.amazonaws.com/application_ecr_repo:v0.1
        ports:
        - containerPort: 5000 # the port your Python app is listening on
        env:
        - name: DBHOST
          value: mysql-service
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
      imagePullSecrets:
        - name: image-secret-reg
