apiVersion: v1
kind: Pod
metadata:
  name: python-mysql-app
spec:
  containers:
  - name: python-app
    image: python:3.9
    command: ["python3", "app.py"]
    env:
    - name: DBUSER
      value: root
    - name: DBPWD
      value: "passwors"
    - name: DBHOST
      value: "mysql.database.svc.cluster.local"
    - name: DATABASE
      value: "employees"
    ports:
    - containerPort: 5000
  - name: mysql
    image: 987242725346.dkr.ecr.us-east-1.amazonaws.com/database_ecr_repo:v0.1
    env:
    - name: DBPWD
      value:  "passwors"
    - name: DATABASE
      value: "employees"
    ports:
    - containerPort: 3306
   
