apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: employees-replicaset
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: employees-replicaset
        image: 987242725346.dkr.ecr.us-east-1.amazonaws.com/application_ecr_repo:v0.1
        env:
        - name: DBUSER
          value: root
        - name: DBPWD
          value: "passwors"
        - name: DBHOST
          value: "mysql.database.svc.cluster.local"
        - name: DATABASE
          value: "employees"
        ports:
        - containerPort: 8080
     
      
