apiVersion: v1
kind: Service
metadata:
  name: my-python-mysql-app
  labels:
    app: my-python-mysql-app
spec:
  selector:
    app: my-python-mysql-app
  ports:
    - name: http
      port: 80
      targetPort: 5000
    - name: mysql
      port: 3306
      targetPort: 3306
  type: NodePort