name: Deploy to the ECR

on: 
  push:
    branches: [ master ]

jobs:

  build:
    
    name: Build Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-app/
    
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1
        WORKING_DIR: web-app/

    - name: Build, test, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY_ONE: application_ecr_repo
        ECR_REPOSITORY_TWO: database_ecr_repo
        IMAGE_TAG: v0.1
        WORKING_DIR: web-app/
      run: |
        # Docker builD
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_ONE:$IMAGE_TAG .
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_TWO:$IMAGE_TAG -f Dockerfile_mysql .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_ONE:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_TWO:$IMAGE_TAG
